# Code Generated by Sidekick is for learning and experimentation purposes only.

from __future__ import annotations

from typing import Any

import chromadb  # type: ignore[import-untyped]
from chromadb.config import Settings as ChromaSettings  # type: ignore[import-untyped]

from app.config import get_settings

_client: Any = None


def get_chroma_client() -> Any:
    global _client
    if _client is None:
        settings = get_settings()
        _client = chromadb.PersistentClient(
            path=settings.chroma_persist_dir,
            settings=ChromaSettings(anonymized_telemetry=False),
        )
    return _client


def get_documents_collection(project_id: str) -> Any:
    """One logical collection with project_id metadata filter."""
    client = get_chroma_client()
    return client.get_or_create_collection(
        name="documents",
        metadata={"hnsw:space": "cosine"},
    )


def get_patterns_collection() -> Any:
    """Global patterns knowledge base collection."""
    client = get_chroma_client()
    return client.get_or_create_collection(
        name="patterns",
        metadata={"hnsw:space": "cosine"},
    )