# Code Generated by Sidekick is for learning and experimentation purposes only.

from __future__ import annotations

import os
from pathlib import Path
from functools import lru_cache

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    # Auth
    secret_key: str = "change-me-to-a-long-random-string"
    jwt_algorithm: str = "HS256"
    access_token_expire_minutes: int = 1440  # 24 h

    # Single-user credentials (seeded on first startup)
    admin_username: str = "admin"
    admin_password: str = "admin"

    # Database
    database_url: str = "sqlite+aiosqlite:///./data/agent_factory.db"
    checkpoint_db_path: str = "./data/checkpoints.sqlite"

    # ChromaDB
    chroma_persist_dir: str = "./data/chroma"

    # File storage
    upload_dir: str = "./data/projects"
    max_upload_size_mb: int = 50

    # OpenAI
    openai_api_key: str = ""
    openai_model: str = "gpt-4o"
    embedding_model: str = "text-embedding-3-small"
    # JSON map of model -> {input, output} USD per 1M tokens
    model_pricing: str = ""

    # Cost ceilings (0 = disabled)
    max_tokens_per_run: int = 500000
    max_cost_usd_per_run: float = 25.0

    # Sentence Transformers (HuggingFace) — used for Pattern KB embeddings
    sentence_transformer_model: str = "all-MiniLM-L6-v2"

    # Workflow settings
    max_clarification_rounds: int = 3
    max_critic_rounds: int = 3
    complexity_threshold: int = 5  # FR count above this → heavyweight path
    max_code_retries: int = 2     # per-task reviewer retry cap in W3
    ws_ping_interval: int = 20
    ws_pong_timeout: int = 10

    @property
    def max_upload_bytes(self) -> int:
        return self.max_upload_size_mb * 1024 * 1024

    @property
    def base_data_dir(self) -> Path:
        return Path(self.upload_dir)


@lru_cache
def get_settings() -> Settings:
    return Settings()